# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from golang v1.11 base image
FROM golang:1.11

# Add Maintainer Info
LABEL maintainer="Rajeev Singh <rajeevhub@gmail.com>"

# Download and install dep
ADD https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

# Set the Current Working Directory inside the container
WORKDIR $GOPATH/src/github.com/callicoder/go-docker

# COPY dependencies file and install all dependencies
COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure --vendor-only

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . .

# Building the package
RUN go build -o ./out/go-docker .

# This container exposes port 8080 to the outside world
EXPOSE 8080

# Run the built binary executable
CMD ["./out/go-docker"]
